# Generated by Django 3.1.6 on 2021-02-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshcart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='person',
            field=models.CharField(max_length=50),
        ),
    ]
